apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ig8x
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ig8x
    app.kubernetes.io/part-of: tkwch-fix-0075-0072-app
  name: devfile-sample-ig8x
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ig8x
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ig8x
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0072-tenant/tkwch-fix-0075-0072-app/devfile-sample-ig8x@sha256:181debb973001c536f79b36ac3d32945f5a95d7fa158928ffe5304c9b20555d4
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
