apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ig8x
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0072-tenant/tkwch-fix-0075-0072-app/devfile-sample-ig8x@sha256:181debb973001c536f79b36ac3d32945f5a95d7fa158928ffe5304c9b20555d4
        name: my-nodejs
        resources: {}
status: {}
